version: '3.8'
services:
  data-collector:
    build: ./data-collector
    env_file:
      - ./data-collector/.env
    restart: unless-stopped

  nextjs-app:
    build: ./nextjs-app
    env_file:
      - ./nextjs-app/.env
    ports:
      - "3000:3000"
    restart: unless-stopped 