version: '3.8'
services:
  data-collector:
    build: ./data-collector
    env_file:
      - ./data-collector/.env
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 1m

  nextjs-app:
    build: ./nextjs-app
    env_file:
      - ./nextjs-app/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - data-collector 