name: CI/CD Pipeline for Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure-vm:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Docker 이미지 빌드
    - name: Build Docker image
      run: |
        docker build -t rkseksgksl/nodeweb:latest .

    # 3. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Docker 이미지 푸시
    - name: Push Docker image to Docker Hub
      run: |
        docker push rkseksgksl/nodeweb:latest

    # 5. Azure VM에 SSH로 접속하여 컨테이너 업데이트
    - name: Copy .env to Azure VM
      uses: appleboy/scp-action@v0.1.0
      with:
        host: "20.168.3.131"
        username: "azureuser"
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        source: ./webserver/.env
        target: /home/azureuser/webserver/.env

    # 6. Update Docker run command to use the correct .env path
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: "20.168.3.131"
        username: "azureuser"
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          sudo docker pull rkseksgksl/nodeweb:latest
          sudo docker stop nodeweb || true
          sudo docker rm nodeweb || true
          sudo docker run -d -p 80:3000 --name nodeweb --env-file /home/azureuser/webserver/.env rkseksgksl/nodeweb:latest
