name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

      - name: Deploy and restart services
        env:
          REPO_URL: git@github.com:NamidaEro/webserver.git
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} '
            if [ ! -d "/home/azureuser/webserver/.git" ]; then
              git clone $REPO_URL /home/azureuser/webserver;
            else
              cd /home/azureuser/webserver && git pull;
            fi
            cd /home/azureuser/webserver
            docker-compose build
            docker-compose up -d
          '
